name: notion_inbox
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  collection: ^1.18.0
  core_y:
    git:
      url: https://github.com/Yogi-7y/Project-Y.git
      path: packages/core
      ref: core_v1.0.1

  envied: ^0.5.4+1
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.5.1
  meta: ^1.10.0

  network_y:
    git:
      url: https://github.com/Yogi-7y/Project-Y.git
      path: packages/network
      ref: network_v1.0.1

  smart_textfield:
    git:
      url: https://github.com/Yogi-7y/Project-Y.git
      path: packages/smart_textfield
      ref: smart_textfield_v1.0.4

dependency_overrides:
  core_y:
    # path: ../project_y/packages/core
    git:
      url: https://github.com/Yogi-7y/Project-Y.git
      path: packages/core
      ref: core_v1.0.2
  network_y:
    # path: ../project_y/packages/network
    git:
      url: https://github.com/Yogi-7y/Project-Y.git
      path: packages/network
      ref: network_v1.0.3

dev_dependencies:
  build_runner: ^2.4.9
  envied_generator: ^0.5.4+1
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  lints_y:
    git:
      url: https://github.com/Yogi-7y/Project-Y.git
      path: packages/lints
      ref: lints_v1.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/launcher_icon/plus_launcher_icon.png
